### ISSUE TITLE
Prepare Solidus Sale Prices for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_sale_prices#51]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by SamuelMartini** [comment]
Taking care of this!

**Comment by jarednorman** [comment]
This extension relies on legacy pricing logic and I don't _think_ it can work with Solidus 3.0. In order to move off `price_in` it needs the price selector to return a `Spree::Price` and we don't intend to merge that change until 3.1.

It can't even modify the price selector to add the API it needs, as that's a configurable class.

I'm not actually sure what to do here. As far as I can tell, our stores that use this extension will have to do some hackery to make this work on Solidus 3.0, or just 🤷🏻‍♂️ and wait for 3.1.

**Comment by jarednorman** [comment]
I guess it only worked with the default price selector before, actually... so maybe it's possible to maintain that since we know what the default selector does.

Lame caveat, but I guess it is solvable at least in that case.

**Comment by jarednorman** [comment]
Sorry, just thinking through this:

Because it only ever selected prices by currency, we can maintain that for v3.0 and then ideally create a new major release that leverages the pricing selector's new API in v3.1, which would be a big step forward for this gem.
